create table if not exists "users" (
  "user_id" int generated by default as identity primary key,
  "clerk_id" varchar unique not null,
  "full_name" varchar not null,
  "email" varchar unique not null,
  "phone" varchar,
  "role" varchar not null,
  "profile_photo" varchar,
  "is_verified" boolean default false,
  "is_active" boolean default true,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz
);

create table if not exists "seeker_profiles" (
  "seeker_id" int generated by default as identity primary key,
  "user_id" int not null references "users" ("user_id"),
  "gender" varchar,
  "age" int,
  "occupation" varchar,
  "bio" text,
  "smoking" varchar,
  "drinking" varchar,
  "sleep_schedule" varchar,
  "cleanliness" int,
  "preferred_gender" varchar,
  "age_min" int,
  "age_max" int,
  "pet_friendly" boolean default false,
  "roommate_notes" text,
  "updated_at" timestamptz
);

create table if not exists "seeker_preferred_locations" (
  "location_id" int generated by default as identity primary key,
  "seeker_id" int not null references "seeker_profiles" ("seeker_id"),
  "location_name" varchar not null,
  "lat" decimal,
  "lng" decimal,
  "priority" int default 1
);

create table if not exists "owner_profiles" (
  "owner_id" int generated by default as identity primary key,
  "user_id" int not null references "users" ("user_id"),
  "business_name" varchar,
  "owner_type" varchar,
  "bio" text,
  "kyc_status" varchar default 'pending',
  "is_verified" boolean default false,
  "updated_at" timestamptz
);

create table if not exists "kyc_documents" (
  "kyc_id" int generated by default as identity primary key,
  "owner_id" int not null references "owner_profiles" ("owner_id"),
  "id_type" varchar,
  "id_number" varchar,
  "id_front_url" varchar,
  "id_back_url" varchar,
  "address_doc_type" varchar,
  "address_doc_url" varchar,
  "submitted_at" timestamptz default now(),
  "reviewed_at" timestamptz,
  "reviewer_notes" text
);

create table if not exists "current_room_details" (
  "room_id" int generated by default as identity primary key,
  "user_id" int not null references "users" ("user_id"),
  "has_room" boolean default false,
  "room_type" varchar,
  "location" varchar,
  "lat" decimal,
  "lng" decimal,
  "rent" decimal,
  "vacancy" int default 0,
  "description" text,
  "available_from" date,
  "preferred_gender" varchar,
  "pet_friendly" boolean default false,
  "smoking_allowed" boolean default false,
  "status" varchar default 'active',
  "created_at" timestamptz default now(),
  "updated_at" timestamptz
);

create table if not exists "current_room_amenities" (
  "id" int generated by default as identity primary key,
  "room_id" int not null references "current_room_details" ("room_id"),
  "amenity" varchar
);

create table if not exists "current_room_images" (
  "id" int generated by default as identity primary key,
  "room_id" int not null references "current_room_details" ("room_id"),
  "image_url" varchar not null,
  "order_no" int default 0
);

create table if not exists "properties" (
  "property_id" int generated by default as identity primary key,
  "owner_id" int not null references "owner_profiles" ("owner_id"),
  "title" varchar not null,
  "description" text,
  "property_type" varchar,
  "room_type" varchar,
  "listing_type" varchar,
  "promotion_type" varchar default 'standard',
  "address" varchar,
  "city" varchar,
  "state" varchar,
  "lat" decimal,
  "lng" decimal,
  "monthly_rent" decimal not null,
  "security_deposit" decimal,
  "maintenance_charges" decimal,
  "available_from" date,
  "minimum_stay_months" int default 1,
  "total_rooms" int,
  "available_rooms" int,
  "bathrooms" int,
  "balcony" boolean default false,
  "furnishing" varchar,
  "cover_image" varchar,
  "status" varchar default 'active',
  "total_views" int default 0,
  "created_at" timestamptz default now(),
  "updated_at" timestamptz
);

create table if not exists "property_amenities" (
  "id" int generated by default as identity primary key,
  "property_id" int not null references "properties" ("property_id"),
  "amenity" varchar
);

create table if not exists "property_images" (
  "id" int generated by default as identity primary key,
  "property_id" int not null references "properties" ("property_id"),
  "image_url" varchar not null,
  "order_no" int default 0
);

create table if not exists "roommate_matches" (
  "match_id" int generated by default as identity primary key,
  "seeker_id" int not null references "users" ("user_id"),
  "matched_user_id" int not null references "users" ("user_id"),
  "compatibility" int,
  "status" varchar default 'suggested',
  "created_at" timestamptz default now()
);

create table if not exists "saved_items" (
  "id" int generated by default as identity primary key,
  "user_id" int not null references "users" ("user_id"),
  "item_type" varchar,
  "item_id" int not null,
  "saved_at" timestamptz default now()
);

create table if not exists "conversations" (
  "conversation_id" int generated by default as identity primary key,
  "sender_id" int not null references "users" ("user_id"),
  "receiver_id" int not null references "users" ("user_id"),
  "context_type" varchar,
  "context_id" int,
  "status" varchar default 'pending',
  "created_at" timestamptz default now(),
  "updated_at" timestamptz
);

create table if not exists "messages" (
  "message_id" int generated by default as identity primary key,
  "conversation_id" int not null references "conversations" ("conversation_id"),
  "sender_id" int not null references "users" ("user_id"),
  "body" text not null,
  "is_read" boolean default false,
  "sent_at" timestamptz default now()
);

create table if not exists "inquiries" (
  "inquiry_id" int generated by default as identity primary key,
  "user_id" int not null references "users" ("user_id"),
  "property_id" int not null references "properties" ("property_id"),
  "message" text,
  "status" varchar default 'pending',
  "created_at" timestamptz default now()
);

create table if not exists "notifications" (
  "notification_id" int generated by default as identity primary key,
  "user_id" int not null references "users" ("user_id"),
  "type" varchar,
  "title" varchar,
  "body" text,
  "is_read" boolean default false,
  "created_at" timestamptz default now()
);

create table if not exists "property_views" (
  "view_id" int generated by default as identity primary key,
  "property_id" int not null references "properties" ("property_id"),
  "viewer_id" int references "users" ("user_id"),
  "viewed_at" timestamptz default now()
);

create table if not exists "property_analytics" (
  "id" int generated by default as identity primary key,
  "property_id" int not null references "properties" ("property_id"),
  "date" date not null,
  "views" int default 0,
  "inquiries" int default 0
);

create or replace function increment_property_views(target_property_id int)
returns void
language plpgsql
as $$
begin
  update properties
  set total_views = coalesce(total_views, 0) + 1
  where property_id = target_property_id;
end;
$$;

create index if not exists idx_properties_city on properties(city);
create index if not exists idx_properties_status on properties(status);
create index if not exists idx_roommate_matches_seeker on roommate_matches(seeker_id);
create index if not exists idx_roommate_matches_matched on roommate_matches(matched_user_id);
create index if not exists idx_messages_conversation on messages(conversation_id);
create index if not exists idx_notifications_user on notifications(user_id);
